In [16]:
import numpy as np
import scipy
from scipy import linalg

In [3]:
np.mgrid[0:5, 0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [15]:
# numpy matrices
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [17]:
# inverse
linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [20]:
B = np.array([[5,6]])
B

array([[5, 6]])

In [23]:
# transpose
B.T

array([[5],
       [6]])

In [24]:
# multiplication
A.dot(B.T)

array([[17],
       [39]])

### solving linear equations
1. x + 3y + 5z = 10
2. 2x + 5y + z = 8
3. 2x + 3y + 8z = 3

In [26]:
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [32]:
B = np.array([[10,8,3]])
B

array([[10,  8,  3]])

In [34]:
# solution is inverse(A) * B.T
sol = linalg.inv(A).dot(B.T)
sol

array([[-9.28],
       [ 5.16],
       [ 0.76]])

In [35]:
# faster way of doing that is
linalg.solve(A, B.T)

array([[-9.28],
       [ 5.16],
       [ 0.76]])

### Determinant

In [37]:
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [38]:
linalg.det(A)

-25.000000000000004

### norms

In [45]:
# L1 norm
linalg.norm([1,-2,-3,4], 1)

10

In [46]:
# L2 norm
linalg.norm([1,-2,-3,4,5], 2)

7.416198487095663