In [2]:
import numpy as np
import scipy
from scipy import linalg

In [3]:
np.mgrid[0:5, 0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [15]:
# numpy matrices
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [17]:
# inverse
linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [20]:
B = np.array([[5,6]])
B

array([[5, 6]])

In [23]:
# transpose
B.T

array([[5],
       [6]])

In [24]:
# multiplication
A.dot(B.T)

array([[17],
       [39]])

### solving linear equations
1. x + 3y + 5z = 10
2. 2x + 5y + z = 8
3. 2x + 3y + 8z = 3

In [26]:
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [32]:
B = np.array([[10,8,3]])
B

array([[10,  8,  3]])

In [34]:
# solution is inverse(A) * B.T
sol = linalg.inv(A).dot(B.T)
sol

array([[-9.28],
       [ 5.16],
       [ 0.76]])

In [35]:
# faster way of doing that is
linalg.solve(A, B.T)

array([[-9.28],
       [ 5.16],
       [ 0.76]])

### Determinant

In [37]:
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [38]:
linalg.det(A)

-25.000000000000004

### norms

In [45]:
# L1 norm
linalg.norm([1,-2,-3,4], 1)

10

In [46]:
# L2 norm
linalg.norm([1,-2,-3,4,5], 2)

7.416198487095663

### Numpy Arrays

In [5]:
A = np.array([1.2, .2, 2.])

In [6]:
sum(A)

3.3999999999999999

In [7]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)
M

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [8]:
M.transpose()

array([[ 1.,  4.,  7.],
       [ 2.,  5.,  8.],
       [ 3.,  6.,  9.]])

In [9]:
A.shape

(3,)

In [10]:
M.shape

(3, 3)

### element wise operations

In [13]:
A

array([ 1.2,  0.2,  2. ])

In [14]:
A+5.0

array([ 6.2,  5.2,  7. ])

In [15]:
A + [1,2,3]

array([ 2.2,  2.2,  5. ])

In [16]:
A**2

array([ 1.44,  0.04,  4.  ])

In [21]:
A/2.0

array([ 0.6,  0.1,  1. ])

### matrix operations

In [22]:
np.dot(M, A)

array([  7.6,  17.8,  28. ])

In [23]:
np.outer(A, [10, 20, 30])

array([[ 12.,  24.,  36.],
       [  2.,   4.,   6.],
       [ 20.,  40.,  60.]])

### accessing

In [24]:
M[0,1]

2.0

In [29]:
# 1st row
print "1st row:", M[:,1]

# 2nd col
print "1nd col:", M[1,:]

1st row: [ 2.  5.  8.]
1nd col: [ 4.  5.  6.]


In [31]:
M[0:2, :]

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [33]:
# provide indices 
M[[0,2], :]

array([[ 1.,  2.,  3.],
       [ 7.,  8.,  9.]])

In [36]:
A[::-1]

array([ 2. ,  0.2,  1.2])

### Special case for rank 1 matrices

In [41]:
# rank 1 matrices are sequences and are automatically transposed as necessary
print np.all(M==M.T)
print np.all(A==A.T)

False
True


In [43]:
np.all(np.dot(M, A) == np.dot(M, A.T))

True

### creating arrays

In [45]:
np.arange(0, 8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [46]:
np.arange(3,8,2)

array([3, 5, 7])

In [47]:
np.linspace(-20, 20, 5)

array([-20., -10.,   0.,  10.,  20.])

In [49]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [50]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [52]:
# identity
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [62]:
# a & b are matrices
def multiply(a, b):
    return a*b
np.fromfunction(multiply, (3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  1.,  2.],
       [ 0.,  2.,  4.]])

### changing shape

In [64]:
Z = np.arange(8)
Z

array([0, 1, 2, 3, 4, 5, 6, 7])

In [65]:
Z.shape

(8,)

In [67]:
Z.shape = (2,4)
Z

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [81]:
Z.reshape(2,2, -1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [84]:
Z[:,0]

array([0, 4])

### copying arrays

In [87]:
X = np.arange(8)
X

array([0, 1, 2, 3, 4, 5, 6, 7])

In [89]:
Y = X
Y

array([0, 1, 2, 3, 4, 5, 6, 7])

In [90]:
Y[0] = -5
X

array([-5,  1,  2,  3,  4,  5,  6,  7])

In [91]:
Z = X[2:5]
Z

array([2, 3, 4])

In [92]:
Z[0] = 100
X

array([ -5,   1, 100,   3,   4,   5,   6,   7])

In [93]:
Y

array([ -5,   1, 100,   3,   4,   5,   6,   7])

In [96]:
X = np.arange(8)
Z = X[2.:5].copy()
Z[0] = 100
print "Z:",Z
print "X:", X

Z: [100   3   4]
X: [0 1 2 3 4 5 6 7]
