### http://www.cs.ubc.ca/~nando/340-2012/lectures.php
#### Probability

In [26]:
from __future__ import division
import random
from collections import Counter
import time
import numpy as np

In [12]:
random.seed(time.time())

def flip_coin():
    return random.choice(['H', 'T'])

In [14]:
# frequentist determination of P(H) or P(T)
c = Counter()
for x in xrange(100000):
    c[flip_coin()] +=1
c

Counter({'H': 49999, 'T': 50001})

In [15]:
omega_die = {1,2,3,4,5,6}
omega_coin = {'H', 'T'}

In [18]:
even = {2,4,6}
P_even = len(even) / len(omega_die)
print P_even

0.5


In [19]:
greater_than_four = {5,6}
print len(greater_than_four) / len(omega_die)

0.333333333333


In [20]:
# conditional probability example
bag = ['r','r','r', 'b']

In [22]:
# probabilty of drawing 2 red balls in the first two tries without replacement
# p(B1=r, B2=r) = P(B2=r | B1=r)*P(B1=r)
print (2/3)*(3/4)

0.5


In [25]:
# Marginalization
# E.g. probability that second ball will be red
# P(B2=r) = P(B2=r, B1=r) + P(B1=r, B1=b)
(2/3)*(3/4) + (1)*(1/4)

0.75

In [34]:
# Matrix notation ( from our example above)
# P(x1=0)=3/4 P(x1=1) = 1/4
# assume that P(x2=1|X1=0)=1/3 and P(X2=1|X1=1) = 0 and P(X2=0|X1=0) = 2/3 and P(X2=0|X1=1) = 1

X1 = np.array([[3/4, 1/4]])

In [39]:
X2 = np.array([[2/3, 1/3],[0, 1]])

In [40]:
X1

array([[ 0.75,  0.25]])

In [41]:
X2

array([[ 0.66666667,  0.33333333],
       [ 0.        ,  1.        ]])

In [42]:
# P(x2) = X1 * X2
X1.dot(X2)

array([[ 0.5,  0.5]])